import React, { useState, useEffect } from 'react';
import { Search, Plus, Loader2, X, User, Shield, Briefcase } from 'lucide-react';
import { supabase } from '../lib/supabase';

export default function MasterNomina() {
  const [profiles, setProfiles] = useState([]);
  const [roles, setRoles] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [flashColor, setFlashColor] = useState('');

  // Modal State
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [editingId, setEditingId] = useState(null);
  const [searchQuery, setSearchQuery] = useState('');
  
  const initialForm = {
    full_name: '',
    role: '',
    is_auth_user: false
  };
  const [formData, setFormData] = useState(initialForm);

  const triggerFlash = (type) => {
    setFlashColor(type === 'success' ? 'bg-brand-success' : 'bg-brand-error');
    setTimeout(() => setFlashColor(''), 150);
  };

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      setLoading(true);
      const [profilesRes, rolesRes] = await Promise.all([
        supabase.from('profiles').select('*').order('full_name', { ascending: true }),
        supabase.from('master_staff_roles').select('name').eq('active', true).order('name', { ascending: true })
      ]);

      if (profilesRes.error) throw profilesRes.error;
      if (rolesRes.error) throw rolesRes.error;

      setProfiles(profilesRes.data || []);
      setRoles(rolesRes.data || []);
    } catch (err) {
      console.error('Error fetching data:', err);
      setError(err.message);
      triggerFlash('error');
    } finally {
      setLoading(false);
    }
  };

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData(prev => ({ 
      ...prev, 
      [name]: type === 'checkbox' ? checked : value 
    }));
  };

  const handleSave = async (e) => {
    e.preventDefault();
    if (!formData.full_name || !formData.role) return;

    try {
      setIsSaving(true);
      
      const payload = { 
        full_name: formData.full_name,
        role: formData.role,
        is_auth_user: formData.is_auth_user,
      };

      if (editingId) {
        // Update existing
        const { error } = await supabase
          .from('profiles')
          .update(payload)
          .eq('id', editingId);
        if (error) throw error;
      } else {
        // Insert new (UUID autogenerated by Postgres, or we explicitly insert if needed)
        // Since is_auth_user is false, it might not need matching auth.users row
        payload.id = crypto.randomUUID(); 
        payload.active = true;

        const { error } = await supabase
          .from('profiles')
          .insert([payload]);
        if (error) throw error;
      }

      triggerFlash('success');
      setIsModalOpen(false);
      setFormData(initialForm);
      fetchData(); // Refresh list
    } catch (err) {
      console.error('Error saving profile:', err);
      triggerFlash('error');
    } finally {
      setIsSaving(false);
    }
  };

  const toggleStatus = async (id, currentStatus) => {
    try {
      const { error } = await supabase
        .from('profiles')
        .update({ active: !currentStatus })
        .eq('id', id);
        
      if (error) throw error;
      
      triggerFlash('success');
      setProfiles(profiles.map(p => p.id === id ? { ...p, active: !currentStatus } : p));
    } catch (err) {
      console.error('Error toggling status:', err);
      triggerFlash('error');
    }
  };

  return (
    <div className="h-full flex flex-col p-8 min-h-full relative">
      {/* Interaction Flash Overlay */}
      {flashColor && <div className={`fixed inset-0 z-50 pointer-events-none opacity-10 transition-opacity duration-150 ${flashColor}`}></div>}

      <div className="flex justify-between items-end mb-8 shrink-0">
        <div>
          <h2 className="text-3xl font-extrabold tracking-tight text-brand-text">Nómina de Personal</h2>
          <p className="text-sm font-semibold text-brand-muted mt-1">Gestión centralizada de perfiles y accesos (Master)</p>
        </div>
        <div className="flex gap-3">
          <div className="relative">
            <Search size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-brand-muted" />
            <input 
              type="text" 
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Buscar por nombre o rol..." 
              className="pl-10 pr-4 py-2.5 rounded-xl bg-brand-bg border border-brand-border text-sm font-semibold focus:outline-none focus:border-brand-text focus:ring-1 focus:ring-brand-text/50 placeholder:text-brand-muted text-brand-text w-72 transition-all"
            />
          </div>
          <button 
            onClick={() => {
              setFormData(initialForm);
              setEditingId(null);
              setIsModalOpen(true);
            }} 
            className="flex items-center gap-2 px-4 py-2.5 rounded-xl border border-transparent bg-brand-text text-brand-bg text-sm font-bold hover:bg-brand-text/90 transition-all duration-200 cursor-pointer shadow-md"
          >
            <Plus size={18} />
            Nuevo Perfil
          </button>
        </div>
      </div>

      <div className="flex-1 border border-brand-border bg-brand-bg rounded-2xl overflow-hidden flex flex-col shadow-sm">
        <div className="overflow-x-auto h-full">
          <table className="w-full text-left text-sm whitespace-nowrap border-collapse">
            <thead className="bg-[#0A0A0A] text-brand-muted sticky top-0 z-10 border-b border-brand-border">
              <tr>
                <th className="p-4 pl-6 text-[10px] font-extrabold uppercase tracking-widest">Nombre Completo</th>
                <th className="p-4 text-[10px] font-extrabold uppercase tracking-widest">Rol Asignado</th>
                <th className="p-4 text-[10px] font-extrabold uppercase tracking-widest text-center">Usuario Auth</th>
                <th className="p-4 text-[10px] font-extrabold uppercase tracking-widest text-center">Estado</th>
                <th className="p-4 text-[10px] font-extrabold uppercase tracking-widest text-right pr-6">Acciones</th>
              </tr>
            </thead>
            <tbody className="font-medium relative divide-y divide-brand-border/50">
              {loading ? (
                <tr>
                  <td colSpan="5" className="p-12 text-center text-brand-muted">
                    <Loader2 size={32} className="animate-spin mx-auto mb-4 text-brand-text" />
                    <div className="uppercase tracking-widest text-xs font-bold">Sincronizando Nómina...</div>
                  </td>
                </tr>
              ) : error ? (
                <tr>
                  <td colSpan="5" className="p-12 text-center text-brand-error">
                    <div className="uppercase tracking-widest text-xs font-bold">Error de conexión: {error}</div>
                  </td>
                </tr>
              ) : profiles.length === 0 ? (
                <tr>
                  <td colSpan="5" className="p-12 text-center text-brand-muted">
                    <div className="uppercase tracking-widest text-xs font-bold">No hay personal registrado.</div>
                  </td>
                </tr>
              ) : (
                profiles
                  .filter(p => 
                    (p.full_name?.toLowerCase() || '').includes(searchQuery.toLowerCase()) || 
                    (p.role?.toLowerCase() || '').includes(searchQuery.toLowerCase())
                  )
                  .map((profile) => (
                    <tr key={profile.id} className={`hover:bg-brand-surface/30 transition-all duration-200 group ${!profile.active ? 'opacity-50 grayscale' : ''}`}>
                      <td className="p-4 pl-6 font-bold text-sm text-brand-text flex items-center gap-3">
                        <div className="w-8 h-8 rounded-full bg-brand-surface border border-brand-border flex items-center justify-center shrink-0">
                          <User size={14} className="text-brand-muted" />
                        </div>
                        {profile.full_name}
                      </td>
                      <td className="p-4 text-xs font-bold text-brand-muted uppercase tracking-widest">
                        <span className="px-2.5 py-1 bg-brand-surface rounded-md border border-brand-border/50">
                          {(profile.role || 'SIN ROL').replace(/^STAFF_/i, '').replace(/_/g, ' ')}
                        </span>
                      </td>
                      <td className="p-4 text-center">
                        {profile.is_auth_user ? (
                           <Shield size={16} className="text-brand-success mx-auto" title="Usuario del Sistema" />
                        ) : (
                           <span className="text-brand-muted text-lg leading-none">-</span>
                        )}
                      </td>
                      <td className="p-4 text-center">
                        <div className="flex justify-center">
                          <button 
                            onClick={() => toggleStatus(profile.id, profile.active)}
                            className={`w-12 h-6 rounded-full relative transition-colors cursor-pointer ${profile.active ? 'bg-brand-success/20' : 'bg-brand-error/20'}`}
                            title={profile.active ? 'Desactivar' : 'Reactivar'}
                          >
                            <span className={`absolute top-1 w-4 h-4 rounded-full transition-all ${profile.active ? 'right-1 bg-brand-success shadow-[0_0_8px_rgba(34,197,94,0.6)]' : 'left-1 bg-brand-error shadow-[0_0_8px_rgba(239,68,68,0.6)]'}`}></span>
                          </button>
                        </div>
                      </td>
                      <td className="p-4 pr-6 text-right">
                        <button 
                          onClick={() => {
                            setFormData({
                              full_name: profile.full_name || '',
                              role: profile.role || '',
                              is_auth_user: profile.is_auth_user || false
                            });
                            setEditingId(profile.id);
                            setIsModalOpen(true);
                          }}
                          className="px-3 py-1.5 rounded-lg text-xs font-bold border border-brand-border text-brand-muted hover:text-brand-text hover:border-brand-text hover:bg-brand-surface transition-all"
                        >
                          EDITAR
                        </button>
                      </td>
                    </tr>
                  ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* MODAL BACKDROP */}
      <div 
        className={`fixed inset-0 bg-black/60 backdrop-blur-sm z-40 transition-opacity duration-300 ${isModalOpen ? 'opacity-100 pointer-events-auto' : 'opacity-0 pointer-events-none'}`}
        onClick={() => setIsModalOpen(false)}
      ></div>

      {/* SLIDE-OVER SIDE SHEET */}
      <div 
        className={`fixed inset-y-0 right-0 w-full max-w-[450px] bg-[#0A0A0A] border-l border-brand-border z-50 flex flex-col shadow-2xl transform transition-transform duration-300 ease-[cubic-bezier(0.25,0.46,0.45,0.94)] ${isModalOpen ? 'translate-x-0' : 'translate-x-full'}`}
      >
        <div className="flex items-center justify-between p-8 border-b border-brand-border/50 shrink-0">
          <div>
            <h2 className="text-xl font-extrabold tracking-widest uppercase text-brand-text">
              {editingId ? 'Editar Perfil' : 'Nuevo Perfil'}
            </h2>
            <p className="text-[10px] uppercase font-bold text-brand-muted tracking-widest mt-1">
              Registro de Personal
            </p>
          </div>
          <button 
            onClick={() => setIsModalOpen(false)}
            className="w-10 h-10 flex items-center justify-center rounded-full hover:bg-brand-surface transition-colors text-brand-muted hover:text-brand-text cursor-pointer"
          >
            <X size={20} />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-8">
          <form id="nominaForm" onSubmit={handleSave} className="space-y-8">
            
            <div className="space-y-6">
              <div className="flex items-center gap-2 border-b border-brand-border/30 pb-2">
                <User size={16} className="text-brand-muted" />
                <h3 className="text-xs font-bold uppercase tracking-widest text-brand-muted">Datos Personales</h3>
              </div>
              <div className="space-y-5">
                <div>
                  <label className="block text-[10px] font-bold text-brand-muted uppercase tracking-widest mb-1">Nombre Completo *</label>
                  <input required type="text" name="full_name" value={formData.full_name} onChange={handleInputChange} className="w-full bg-transparent border-b border-brand-border/50 px-0 py-2 text-base text-brand-text font-bold focus:outline-none focus:border-brand-text transition-colors placeholder-brand-muted/30" placeholder="Ej: Juan Pérez" />
                </div>
              </div>
            </div>

            <div className="space-y-6">
              <div className="flex items-center gap-2 border-b border-brand-border/30 pb-2">
                <Briefcase size={16} className="text-brand-muted" />
                <h3 className="text-xs font-bold uppercase tracking-widest text-brand-muted">Asignación Operativa</h3>
              </div>
              <div className="space-y-5">
                <div>
                  <label className="block text-[10px] font-bold text-brand-muted uppercase tracking-widest mb-1">Rol Operativo *</label>
                  <div className="relative">
                    <select 
                      required 
                      name="role" 
                      value={formData.role} 
                      onChange={handleInputChange} 
                      className="w-full bg-transparent border-b border-brand-border/50 px-0 py-2 text-sm text-brand-text font-semibold focus:outline-none focus:border-brand-text transition-colors appearance-none cursor-pointer" 
                    >
                      <option value="" disabled className="bg-brand-bg text-brand-muted">Seleccionar Rol...</option>
                      {roles.map(r => (
                        <option key={r.name} value={r.name} className="bg-brand-bg">{r.name}</option>
                      ))}
                    </select>
                  </div>
                </div>
              </div>
            </div>

            <div className="space-y-6">
              <div className="flex items-center gap-2 border-b border-brand-border/30 pb-2">
                <Shield size={16} className="text-brand-muted" />
                <h3 className="text-xs font-bold uppercase tracking-widest text-brand-muted">Acceso al Sistema</h3>
              </div>
              <div className="space-y-5">
                <label className="flex items-center justify-between cursor-pointer p-4 rounded-xl border border-brand-border bg-brand-surface/20 hover:bg-brand-surface/40 transition-colors">
                  <div>
                    <div className="text-xs font-bold text-brand-text uppercase tracking-widest">Usuario de Plataforma</div>
                    <div className="text-[10px] font-semibold text-brand-muted mt-1">Permite iniciar sesión en el ERP</div>
                  </div>
                  <div className="relative flex items-center">
                    <input 
                      type="checkbox" 
                      name="is_auth_user" 
                      checked={formData.is_auth_user} 
                      onChange={handleInputChange} 
                      className="sr-only"
                    />
                    <div className={`w-10 h-5 bg-brand-surface rounded-full border border-brand-border transition-colors ${formData.is_auth_user ? 'border-brand-success' : ''}`}></div>
                    <div className={`absolute left-1 top-1 w-3 h-3 bg-brand-muted rounded-full transition-transform ${formData.is_auth_user ? 'translate-x-5 bg-brand-success shadow-[0_0_8px_rgba(34,197,94,0.6)]' : ''}`}></div>
                  </div>
                </label>
              </div>
            </div>

          </form>
        </div>

        <div className="p-8 border-t border-brand-border/50 shrink-0">
          <button 
            type="submit" 
            form="nominaForm"
            disabled={isSaving}
            className={`w-full py-4 rounded-2xl flex items-center justify-center gap-2 font-extrabold uppercase tracking-widest text-sm transition-all duration-200 shadow-2xl ${
              isSaving 
                ? 'bg-brand-text/50 text-brand-bg cursor-not-allowed' 
                : 'bg-brand-text text-brand-bg hover:bg-brand-text/90 cursor-pointer'
            }`}
          >
            {isSaving ? <Loader2 size={18} className="animate-spin" /> : <Plus size={18} />}
            {isSaving ? (editingId ? 'GUARDANDO...' : 'REGISTRANDO...') : (editingId ? 'GUARDAR CAMBIOS' : 'REGISTRAR PERFIL')}
          </button>
        </div>
      </div>
    </div>
  );
}
